version: "3.1"

services:
  etl:
    build:
      context: . #takes dockerfile
    entrypoint: make
    command:
     - run
    volumes:
      - ./data:/app/etl/db/output

  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./data:/metabase-data/metabase.db
    ports:
      - '3000:3000'
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

